name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install ansible-builder
      run: pip install ansible-builder
    - name: Build container image
      run: bin/build_container_image
      env:
        IMAGE_TAG: ${{ github.sha }}
    - name: Setup Bats
      id: setup-bats
      uses: bats-core/bats-action@4.0.0
    - name: Run tests
      run: bats test/*.bats
      env:
        BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        EE_IMAGE: docker.io/manageiq/ansible-ee:${{ github.sha }}
    - name: Push container image
      if: github.ref == 'refs/heads/master' && github.repository_owner == 'ManageIQ'
      run: bin/push_container_image
      env:
        IMAGE_TAG: ${{ github.sha }}
        REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
